/*
 * Generated by Airoha Easy PinMux Tool Version 2.7.2 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2021-06-30 14:57:24:0917
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char HAL_UART0_TXD_PIN = 0;
const char HAL_UART0_TXD_PIN_M_GPIO = 0;
const char HAL_UART0_TXD_PIN_M_UART0_TXD = 1;
const char HAL_UART0_TXD_PIN_M_AUDIO_EXT_SYNC_EN = 5;
const char HAL_UART0_TXD_PIN_M_SPDIF = 7;
const char HAL_UART0_TXD_PIN_M_RF_TEST_P = 8;
const char HAL_UART0_TXD_PIN_M_EINT = 9;
const char HAL_UART0_TXD_PIN_M_DEBUGMON0 = 10;


const char HAL_UART0_RXD_PIN = 1;
const char HAL_UART0_RXD_PIN_M_GPIO = 0;
const char HAL_UART0_RXD_PIN_M_UART0_RXD = 1;
const char HAL_UART0_RXD_PIN_M_SRCLKENAI_FREF = 5;
const char HAL_UART0_RXD_PIN_M_RF_TEST_N = 8;
const char HAL_UART0_RXD_PIN_M_EINT = 9;
const char HAL_UART0_RXD_PIN_M_DEBUGMON1 = 10;


const char HAL_UART2_RXD_PIN = 3;
const char HAL_UART2_RXD_PIN_M_GPIO = 0;
const char HAL_UART2_RXD_PIN_M_AP_JTMS = 1;
const char HAL_UART2_RXD_PIN_M_UART0_CTS = 2;
const char HAL_UART2_RXD_PIN_M_DMIC0_DAT = 3;
const char HAL_UART2_RXD_PIN_M_UART2_RXD = 4;
const char HAL_UART2_RXD_PIN_M_SPI_MST2_CS0 = 5;
const char HAL_UART2_RXD_PIN_M_PAD_DFUNC_SIN = 6;
const char HAL_UART2_RXD_PIN_M_AP_JTDI = 7;
const char HAL_UART2_RXD_PIN_M_CTP1 = 8;
const char HAL_UART2_RXD_PIN_M_EINT = 9;
const char HAL_UART2_RXD_PIN_M_DEBUGMON3 = 10;


const char HAL_UART2_TXD_PIN = 7;
const char HAL_UART2_TXD_PIN_M_GPIO = 0;
const char HAL_UART2_TXD_PIN_M_SPI_MST1_MOSI = 1;
const char HAL_UART2_TXD_PIN_M_SPI_SLV0_MOSI = 2;
const char HAL_UART2_TXD_PIN_M_UART1_RTS = 3;
const char HAL_UART2_TXD_PIN_M_I2S_MST1_MCLK = 4;
const char HAL_UART2_TXD_PIN_M_UART2_TXD = 5;
const char HAL_UART2_TXD_PIN_M_I2C2_SDA = 6;
const char HAL_UART2_TXD_PIN_M_AP_JTCK = 7;
const char HAL_UART2_TXD_PIN_M_AUXADC5 = 8;
const char HAL_UART2_TXD_PIN_M_EINT = 9;
const char HAL_UART2_TXD_PIN_M_DEBUGMON7 = 10;


const char HAL_I2S_SLV0_TX_PIN = 8;
const char HAL_I2S_SLV0_TX_PIN_M_GPIO = 0;
const char HAL_I2S_SLV0_TX_PIN_M_SPI_MST1_MISO = 1;
const char HAL_I2S_SLV0_TX_PIN_M_SPI_SLV0_MISO = 2;
const char HAL_I2S_SLV0_TX_PIN_M_CLKO = 3;
const char HAL_I2S_SLV0_TX_PIN_M_I2S_MST0_TX = 4;
const char HAL_I2S_SLV0_TX_PIN_M_I2S_SLV0_TX = 5;
const char HAL_I2S_SLV0_TX_PIN_M_I2C0_SCL = 6;
const char HAL_I2S_SLV0_TX_PIN_M_DSP_JTMS = 7;
const char HAL_I2S_SLV0_TX_PIN_M_AUXADC4 = 8;
const char HAL_I2S_SLV0_TX_PIN_M_EINT = 9;
const char HAL_I2S_SLV0_TX_PIN_M_DEBUGMON8 = 10;


const char HAL_I2S_SLV0_CK_PIN = 9;
const char HAL_I2S_SLV0_CK_PIN_M_GPIO = 0;
const char HAL_I2S_SLV0_CK_PIN_M_SPI_MST1_SIO2 = 1;
const char HAL_I2S_SLV0_CK_PIN_M_SPI_SLV0_SIO2 = 2;
const char HAL_I2S_SLV0_CK_PIN_M_UART0_CTS = 3;
const char HAL_I2S_SLV0_CK_PIN_M_I2S_MST0_CK = 4;
const char HAL_I2S_SLV0_CK_PIN_M_I2S_SLV0_CK = 5;
const char HAL_I2S_SLV0_CK_PIN_M_I2C0_SDA = 6;
const char HAL_I2S_SLV0_CK_PIN_M_DSP_JTCK = 7;
const char HAL_I2S_SLV0_CK_PIN_M_AUXADC3 = 8;
const char HAL_I2S_SLV0_CK_PIN_M_EINT = 9;
const char HAL_I2S_SLV0_CK_PIN_M_DEBUGMON9 = 10;


const char HAL_I2S_SLV0_WS_PIN = 10;
const char HAL_I2S_SLV0_WS_PIN_M_GPIO = 0;
const char HAL_I2S_SLV0_WS_PIN_M_SPI_MST1_SIO3 = 1;
const char HAL_I2S_SLV0_WS_PIN_M_SPI_SLV0_SIO3 = 2;
const char HAL_I2S_SLV0_WS_PIN_M_UART0_RTS = 3;
const char HAL_I2S_SLV0_WS_PIN_M_I2S_MST0_WS = 4;
const char HAL_I2S_SLV0_WS_PIN_M_I2S_SLV0_WS = 5;
const char HAL_I2S_SLV0_WS_PIN_M_I2C1_SCL = 6;
const char HAL_I2S_SLV0_WS_PIN_M_DSP_JTDI = 7;
const char HAL_I2S_SLV0_WS_PIN_M_AUXADC2 = 8;
const char HAL_I2S_SLV0_WS_PIN_M_EINT = 9;
const char HAL_I2S_SLV0_WS_PIN_M_DEBUGMON10 = 10;


const char HAL_I2S_SLV0_RX_PIN = 11;
const char HAL_I2S_SLV0_RX_PIN_M_GPIO = 0;
const char HAL_I2S_SLV0_RX_PIN_M_SPI_MST1_SCK = 1;
const char HAL_I2S_SLV0_RX_PIN_M_SPI_SLV0_SCK = 2;
const char HAL_I2S_SLV0_RX_PIN_M_UART1_TXD = 3;
const char HAL_I2S_SLV0_RX_PIN_M_I2S_MST0_RX = 4;
const char HAL_I2S_SLV0_RX_PIN_M_I2S_SLV0_RX = 5;
const char HAL_I2S_SLV0_RX_PIN_M_I2C1_SDA = 6;
const char HAL_I2S_SLV0_RX_PIN_M_DSP_JRST = 7;
const char HAL_I2S_SLV0_RX_PIN_M_AUXADC1 = 8;
const char HAL_I2S_SLV0_RX_PIN_M_EINT = 9;
const char HAL_I2S_SLV0_RX_PIN_M_DEBUGMON11 = 10;


const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN = 15;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_GPIO = 0;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_SPI_MST0_MOSI = 1;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_ESC_MOSI = 2;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_MSDC0_DAT0 = 3;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_I2S_MST1_WS = 4;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_I2S_SLV1_WS = 5;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_I2S_MST2_MCLK = 6;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_DMIC1_CLK = 7;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_UART2_TXD = 8;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_EINT = 9;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN_M_DEBUGMON15 = 10;


const char HAL_I2S_MST2_WS_PIN = 16;
const char HAL_I2S_MST2_WS_PIN_M_GPIO = 0;
const char HAL_I2S_MST2_WS_PIN_M_SPI_MST0_MISO = 1;
const char HAL_I2S_MST2_WS_PIN_M_ESC_MISO = 2;
const char HAL_I2S_MST2_WS_PIN_M_MSDC0_DAT1 = 3;
const char HAL_I2S_MST2_WS_PIN_M_I2S_MST2_WS = 4;
const char HAL_I2S_MST2_WS_PIN_M_I2S_SLV2_WS = 5;
const char HAL_I2S_MST2_WS_PIN_M_I2C0_SCL = 6;
const char HAL_I2S_MST2_WS_PIN_M_DMIC1_DAT = 7;
const char HAL_I2S_MST2_WS_PIN_M_UART1_CTS = 8;
const char HAL_I2S_MST2_WS_PIN_M_EINT = 9;
const char HAL_I2S_MST2_WS_PIN_M_DEBUGMON0 = 10;


const char HAL_I2S_MST2_CK_PIN = 17;
const char HAL_I2S_MST2_CK_PIN_M_GPIO = 0;
const char HAL_I2S_MST2_CK_PIN_M_SPI_MST0_SIO2 = 1;
const char HAL_I2S_MST2_CK_PIN_M_ESC_SIO2 = 2;
const char HAL_I2S_MST2_CK_PIN_M_MSDC0_DAT2 = 3;
const char HAL_I2S_MST2_CK_PIN_M_I2S_MST2_CK = 4;
const char HAL_I2S_MST2_CK_PIN_M_I2S_SLV2_CK = 5;
const char HAL_I2S_MST2_CK_PIN_M_I2C0_SDA = 6;
const char HAL_I2S_MST2_CK_PIN_M_MSDC0_CLK1 = 7;
const char HAL_I2S_MST2_CK_PIN_M_UART1_RTS = 8;
const char HAL_I2S_MST2_CK_PIN_M_EINT = 9;
const char HAL_I2S_MST2_CK_PIN_M_DEBUGMON1 = 10;


const char HAL_I2S_MST2_RX_PIN = 18;
const char HAL_I2S_MST2_RX_PIN_M_GPIO = 0;
const char HAL_I2S_MST2_RX_PIN_M_SPI_MST0_SIO3 = 1;
const char HAL_I2S_MST2_RX_PIN_M_ESC_SIO3 = 2;
const char HAL_I2S_MST2_RX_PIN_M_MSDC0_DAT3 = 3;
const char HAL_I2S_MST2_RX_PIN_M_I2S_MST2_RX = 4;
const char HAL_I2S_MST2_RX_PIN_M_I2S_SLV2_RX = 5;
const char HAL_I2S_MST2_RX_PIN_M_I2S_MST1_MCLK = 6;
const char HAL_I2S_MST2_RX_PIN_M_MSDC0_CLK2 = 7;
const char HAL_I2S_MST2_RX_PIN_M_UART2_TXD = 8;
const char HAL_I2S_MST2_RX_PIN_M_EINT = 9;
const char HAL_I2S_MST2_RX_PIN_M_DEBUGMON2 = 10;


const char HAL_I2S_MST2_TX_PIN = 19;
const char HAL_I2S_MST2_TX_PIN_M_GPIO = 0;
const char HAL_I2S_MST2_TX_PIN_M_SPI_MST0_SCK = 1;
const char HAL_I2S_MST2_TX_PIN_M_ESC_SCK = 2;
const char HAL_I2S_MST2_TX_PIN_M_MSDC0_CLK0 = 3;
const char HAL_I2S_MST2_TX_PIN_M_I2S_MST2_TX = 4;
const char HAL_I2S_MST2_TX_PIN_M_I2S_SLV2_TX = 5;
const char HAL_I2S_MST2_TX_PIN_M_I2S_MST0_MCLK = 6;
const char HAL_I2S_MST2_TX_PIN_M_CLKO = 7;
const char HAL_I2S_MST2_TX_PIN_M_UART2_RXD = 8;
const char HAL_I2S_MST2_TX_PIN_M_EINT = 9;
const char HAL_I2S_MST2_TX_PIN_M_DEBUGMON3 = 10;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char EXT_NTC_POWER_SW_PIN = 0xff;
const char EXT_NTC_ADC_PIN = 0xff;
const char EXT_DSP_POWER_SW_PIN = 0xff;
const char EXT_DSP_CLK_SW_PIN = 0xff;
const char EXT_DSP_RTC_CLK_SW_PIN = 0xff;
const char EXT_DSP_32K_CLK_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;
const char BSP_EINTKEY3_PIN = 0xff;
const char BSP_EINTKEY4_PIN = 0xff;
const char BSP_GSENSOR_KEY_PIN = 0xff;
const char BSP_LINE_IN_DET_PIN = 0xff;
const char BSP_LINE_IN_SWITCH_PIN = 0xff;
const char BSP_DETACHABLE_MIC_DET_PIN = 0xff;
const char BSP_IRSENSOR_KEY_PIN = 0xff;
const char BSP_ROTARY_ENCODER0_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER0_PIN_B = 0xff;
const char BSP_ROTARY_ENCODER1_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER1_PIN_B = 0xff;
const char BSP_ROTARY_ENCODER2_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER2_PIN_B = 0xff;
const char BSP_DUAL_CHIP_TRIGGER_RESET_PIN = 0xff;


const char HAL_I2C_MASTER_0_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_0_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_1_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_1_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_2_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_2_SDA_PIN = 0xff;
const char HAL_I2C_AO_SCL_PIN = 0xff;
const char HAL_I2C_AO_SDA_PIN = 0xff;
const char HAL_AUXADC_0_PIN = 0xff;
const char HAL_AUXADC_1_PIN = 0xff;
const char HAL_AUXADC_2_PIN = 0xff;
const char HAL_AUXADC_3_PIN = 0xff;
const char HAL_AUXADC_4_PIN = 0xff;
const char HAL_AUXADC_5_PIN = 0xff;
const char HAL_AUXADC_6_PIN = 0xff;
const char HAL_AUXADC_7_PIN = 0xff;
const char HAL_MSDC_0_CK_PIN = 0xff;
const char HAL_MSDC_0_CM_PIN = 0xff;
const char HAL_MSDC_0_DA0_PIN = 0xff;
const char HAL_MSDC_0_DA1_PIN = 0xff;
const char HAL_MSDC_0_DA2_PIN = 0xff;
const char HAL_MSDC_0_DA3_PIN = 0xff;
const char HAL_PWM_0_PIN = 0xff;
const char HAL_PWM_1_PIN = 0xff;
const char HAL_PWM_2_PIN = 0xff;
const char HAL_PWM_3_PIN = 0xff;
const char HAL_PWM_4_PIN = 0xff;
const char HAL_PWM_5_PIN = 0xff;
const char HAL_PWM_6_PIN = 0xff;
const char HAL_PWM_7_PIN = 0xff;
const char HAL_PWM_8_PIN = 0xff;
const char HAL_PWM_9_PIN = 0xff;
const char HAL_UART0_RTS_PIN = 0xff;
const char HAL_UART0_CTS_PIN = 0xff;
const char HAL_UART1_RXD_PIN = 0xff;
const char HAL_UART1_TXD_PIN = 0xff;
const char HAL_UART1_RTS_PIN = 0xff;
const char HAL_UART1_CTS_PIN = 0xff;
const char HAL_SPI_MASTER0_CS0_PIN = 0xff;
const char HAL_SPI_MASTER0_CS1_PIN = 0xff;
const char HAL_SPI_MASTER0_CS2_PIN = 0xff;
const char HAL_SPI_MASTER0_CS3_PIN = 0xff;
const char HAL_SPI_MASTER0_SCK_PIN = 0xff;
const char HAL_SPI_MASTER0_MISO_PIN = 0xff;
const char HAL_SPI_MASTER0_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER1_CS0_PIN = 0xff;
const char HAL_SPI_MASTER1_CS1_PIN = 0xff;
const char HAL_SPI_MASTER1_CS2_PIN = 0xff;
const char HAL_SPI_MASTER1_CS3_PIN = 0xff;
const char HAL_SPI_MASTER1_SCK_PIN = 0xff;
const char HAL_SPI_MASTER1_MISO_PIN = 0xff;
const char HAL_SPI_MASTER1_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER2_CS0_PIN = 0xff;
const char HAL_SPI_MASTER2_CS1_PIN = 0xff;
const char HAL_SPI_MASTER2_CS2_PIN = 0xff;
const char HAL_SPI_MASTER2_CS3_PIN = 0xff;
const char HAL_SPI_MASTER2_SCK_PIN = 0xff;
const char HAL_SPI_MASTER2_MISO_PIN = 0xff;
const char HAL_SPI_MASTER2_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER2_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER2_SIO3_PIN = 0xff;
const char HAL_SPI_SLV0_CS_PIN = 0xff;
const char HAL_SPI_SLV0_SCK_PIN = 0xff;
const char HAL_SPI_SLV0_MISO_PIN = 0xff;
const char HAL_SPI_SLV0_MOSI_PIN = 0xff;
const char HAL_SPI_SLV0_SIO2_PIN = 0xff;
const char HAL_SPI_SLV0_SIO3_PIN = 0xff;
const char HAL_I2S_MST0_CK_PIN = 0xff;
const char HAL_I2S_MST0_MCLK_PIN = 0xff;
const char HAL_I2S_MST0_RX_PIN = 0xff;
const char HAL_I2S_MST0_TX_PIN = 0xff;
const char HAL_I2S_MST0_WS_PIN = 0xff;
const char HAL_I2S_MST1_CK_PIN = 0xff;
const char HAL_I2S_MST1_MCLK_PIN = 0xff;
const char HAL_I2S_MST1_RX_PIN = 0xff;
const char HAL_I2S_MST1_TX_PIN = 0xff;
const char HAL_I2S_MST1_WS_PIN = 0xff;
const char HAL_I2S_MST2_MCLK_PIN = 0xff;
const char HAL_I2S_MST3_CK_PIN = 0xff;
const char HAL_I2S_MST3_MCLK_PIN = 0xff;
const char HAL_I2S_MST3_RX_PIN = 0xff;
const char HAL_I2S_MST3_TX_PIN = 0xff;
const char HAL_I2S_MST3_WS_PIN = 0xff;
const char HAL_I2S_SLV1_CK_PIN = 0xff;
const char HAL_I2S_SLV1_RX_PIN = 0xff;
const char HAL_I2S_SLV1_TX_PIN = 0xff;
const char HAL_I2S_SLV1_WS_PIN = 0xff;
const char HAL_I2S_SLV2_CK_PIN = 0xff;
const char HAL_I2S_SLV2_RX_PIN = 0xff;
const char HAL_I2S_SLV2_TX_PIN = 0xff;
const char HAL_I2S_SLV2_WS_PIN = 0xff;
const char HAL_I2S_SLV3_CK_PIN = 0xff;
const char HAL_I2S_SLV3_RX_PIN = 0xff;
const char HAL_I2S_SLV3_TX_PIN = 0xff;
const char HAL_I2S_SLV3_WS_PIN = 0xff;





