/*
 * Generated by Airoha Easy PinMux Tool Version 2.6.8 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2020-10-22 18:47:02:0766
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_EINTKEY0_EINT = 8;
const unsigned char BSP_EINTKEY1_EINT = 9;
const unsigned char BSP_EINTKEY2_EINT = 10;
const unsigned char BSP_EINTKEY3_EINT = 11;
const unsigned char BSP_LINE_IN_EINT = 13;
const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char HAL_UART0_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART1_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART2_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DSR_EINT = 0xff;
const unsigned char EXT_DSP_TRIGGER_EINT = 0xff;
const unsigned char BSP_EINTKEY4_EINT = 0xff;
const unsigned char BSP_GSENSOR_KEY_EINT = 0xff;



