/*
 * Generated by Airoha Easy PinMux Tool Version 2.8.1 for AB1568. Copyright Airoha Inc. (C) 2015.
 * 2022-07-26 11:25:06:0503
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
