/*
 * Generated by Airoha Easy PinMux Tool Version 2.6.8 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2020-10-22 18:47:02:0765
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
