/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.1 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2022-06-28 23:18:59:0200
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
