/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.3 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2022-10-12 20:32:06:0139
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
