/* Copyright Statement:
 *
 * (C) 2020  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

/* if it is iic interface,please define this marco */
#ifndef BSP_MULTI_AXIS_SENSOR_CONFIGH_H
#define BSP_MULTI_AXIS_SENSOR_CONFIGH_H
#include "hal.h"
#include "hal_platform.h"
#include <string.h>
#include <stdlib.h>

//#define BSP_MULTI_AXIS_SENSOR_BMI160
//#define BSP_MULTI_AXIS_SENSOR_TDK42607
//#define BSP_MULTI_AXIS_SENSOR_LSM6DSO
//#define BSP_MULTI_AXIS_SENSOR_LSM6DS3
//#define BSP_MULTI_AXIS_SENSOR_LSM6DSOX
#define BSP_MULTI_AXIS_SENSOR_QMI8658


#define AXIS_SENSOR_USED_EPT_CONFIGURATION

/* if you want to start self test when call  bsp_axis_sensor_initialize,please define this marco */
#define AXIS_SENSOR_SELFTEST_ON_INIT_STAGE


extern unsigned char BSP_SENSOR_IN_EINT_0;  /* GPIO_20 */
extern unsigned char BSP_SENSOR_IN_EINT_1;  /* GPIO_18 */

#define AXIS_SENSOR_IIC_PORT HAL_I2C_MASTER_1
#define AXIS_SENSOR_IIC_FREQENCE HAL_I2C_FREQUENCY_400K
/* Generated by Easy PinMux Tool with AG3335A.ews */
extern const char HAL_I2C_MASTER_1_SCL_PIN; /* GPIO_16 */
extern const char HAL_I2C_MASTER_1_SDA_PIN; /* GPIO_17 */

#define AXIS_SENSOR_SPI_PORT        HAL_SPI_MASTER_1
#define AXIS_SENSOR_SPI_FREQENCE    1000000
/* Generated by Easy PinMux Tool with AG3335A.ews */
extern unsigned char HAL_SPI_MASTER1_MOSI_PIN; /* GPIO_12 */
extern unsigned char HAL_SPI_MASTER1_MOSI_PIN_M_SPI_MST1_MOSI;
extern unsigned char HAL_SPI_MASTER1_MISO_PIN; /* GPIO_13 */
extern unsigned char HAL_SPI_MASTER1_SCK_PIN;  /* GPIO_22 */
extern unsigned char HAL_SPI_MASTER1_CS0_PIN;  /* GPIO_23 */

#endif
