/*
 * Generated by MTK Easy PinMux Tool Version 2.5.8 for AB1565. Copyright MediaTek Inc. (C) 2015.
 * 2021-01-18 19:59:40:0871
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
